// NoAI - Content Credentials (C2PA) paa alle websites.
//
// Det her er den eneste del af NoAI der ikke bygger paa en liste over navngivne
// mennesker. Den laeser hvad billedet SELV erklaerer: C2PA-manifestet, som Adobe,
// OpenAI, Google og Leica skriver ind i filen. Vi gaetter ikke - vi kigger efter
// en erklaering nogen har lagt der med vilje.
//
// Vi validerer IKKE signaturen. Til det skal der et helt C2PA-bibliotek og en
// kaede af rodcertifikater, og gevinsten er lille: en forfalsket erklaering om at
// noget ER AI-genereret er ikke et angreb nogen har interesse i at udfoere.
// Vi laeser altsaa erklaeringen, ikke beviset - og siger det med rene ord.

(() => {
  "use strict";

  const MIN_PX = 180;          // avatarer og ikoner er ikke besvaeret vaerd
  const MAX_SAMTIDIGE = 3;
  const CACHE_MAX = 400;       // uden loft vokser den for hver unik URL i fanens levetid
  const MAERKE = "noai-c2pa-mark";

  let taendt = false;
  let doed = false;
  const set = new Map();       // url -> Promise<dom>. IKKE en dom-streng: to <img>
                               // med samme src er almindeligt (CDN-miniaturer, logoer),
                               // og med en streng fik nummer to "pending" som svar og
                               // blev aldrig maerket.
  let ivaerk = 0;
  const koe = [];

  const erDoed = (m) => /context invalidated|Extension context/i.test(m || "");
  const send = (msg) => new Promise((svar) => {
    if (doed) return svar(null);
    try {
      chrome.runtime.sendMessage(msg, (r) => {
        const f = chrome.runtime.lastError;
        if (f) { if (erDoed(f.message)) doed = true; return svar(null); }
        svar(r);
      });
    } catch (e) { if (erDoed(e && e.message)) doed = true; svar(null); }
  });

  const brugbar = (img) =>
    img.currentSrc &&
    /^https?:/.test(img.currentSrc) &&
    img.naturalWidth >= MIN_PX &&
    img.naturalHeight >= MIN_PX;

  function maerk(img, dom) {
    if (dom !== "ai" && dom !== "ai-composite") return;
    if (img.dataset.noaiC2pa === "ai") return;
    img.dataset.noaiC2pa = "ai";
    let vaert = img.parentElement;
    // <picture> tegner kun sit <img> - et indsat <span> ville aldrig kunne ses.
    if (vaert && vaert.tagName === "PICTURE") vaert = vaert.parentElement;
    if (!vaert || vaert.querySelector("." + MAERKE)) return;
    // Vi skriver IKKE i sidens egne styles. At saette position:relative paa en
    // fremmed beholder flytter alle dens absolut placerede boern og oedelaegger
    // layout. Er beholderen ikke i forvejen et anker, springer vi over.
    if (getComputedStyle(vaert).position === "static") { img.dataset.noaiC2pa = "ai-uvist"; return; }
    const m = document.createElement("span");
    m.className = MAERKE;
    // Ordlyden er praecis med vilje: billedet siger det selv, vi har ikke afgjort det.
    // To forskellige paastande, to forskellige maerker. Specifikationen skelner
    // mellem "helt genereret" og "indeholder AI-elementer", og brugeren bryder sig
    // om forskellen.
    m.textContent = dom === "ai-composite" ? "Contains AI — declared" : "AI — declared by the file";
    m.title = (dom === "ai-composite"
        ? "This image carries a Content Credential stating it contains AI-generated elements. "
        : "This image carries a Content Credential stating it was generated by AI. ")
      + "NoAI reads that declaration; it does not verify the signature.";
    vaert.appendChild(m);
  }

  async function undersoeg(img) {
    const url = img.currentSrc;
    if (!set.has(url)) {
      if (set.size >= CACHE_MAX) set.delete(set.keys().next().value);
      set.set(url, send({ type: "c2pa", url }).then((s) => (s && s.verdict) || "none"));
    }
    maerk(img, await set.get(url));
  }

  function naeste() {
    while (ivaerk < MAX_SAMTIDIGE && koe.length) {
      const img = koe.shift();
      ivaerk++;
      undersoeg(img).finally(() => { ivaerk--; naeste(); });
    }
  }

  // Kun billeder der faktisk er i syne. Ellers ville en lang side koste hundredvis
  // af opslag for noget brugeren aldrig ser.
  const iSyne = new IntersectionObserver((poster) => {
    for (const p of poster) {
      if (!p.isIntersecting) continue;
      const img = p.target;
      iSyne.unobserve(img);
      if (brugbar(img)) { koe.push(img); continue; }
      // Et dovent indlaest billede har naturalWidth 0 naar det foerst kommer i syne,
      // fordi det ikke er afkodet endnu. Droppede vi det her, ville funktionen kun
      // virke paa billeder der tilfaeldigvis var faerdige - altsaa naesten ingen paa
      // et moderne, billedtungt website, som er praecis dér den skal virke.
      if (!img.complete || img.naturalWidth === 0) {
        img.addEventListener("load", () => {
          if (!doed && taendt && brugbar(img)) { koe.push(img); naeste(); }
        }, { once: true });
      }
    }
    naeste();
  }, { rootMargin: "200px" });

  function saml() {
    if (!taendt || doed) return;
    for (const img of document.images) {
      if (img.dataset.noaiC2paSet) continue;
      img.dataset.noaiC2paSet = "1";
      iSyne.observe(img);
    }
  }

  let planlagt = false;
  const planlaeg = () => {
    if (planlagt || doed) return;
    planlagt = true;
    const koer = () => { planlagt = false; saml(); };
    if (document.hidden) setTimeout(koer, 500); else requestAnimationFrame(koer);
  };

  async function start() {
    const s = await send({ type: "c2paEnabled" });
    taendt = !!(s && s.enabled);
    if (!taendt) return;
    new MutationObserver(planlaeg).observe(document.documentElement,
      { childList: true, subtree: true });
    planlaeg();
  }

  chrome.storage.onChanged.addListener((c, o) => {
    if (o !== "local" || !c.c2pa || doed) return;
    // Tidligere stod her location.reload(). Scriptet koerer paa http(s)://*/*, saa
    // ét klik paa kontakten genindlaeste HVER aaben fane samtidig: tabte formularer,
    // tabt scroll-position, afbrudt video. Paa en maskine med 40 faner ligner det
    // et browser-nedbrud.
    taendt = !!c.c2pa.newValue;
    if (taendt) planlaeg();
    else for (const m of document.querySelectorAll("." + MAERKE)) m.remove();
  });

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();
})();
