// NoAI - Content Credentials (C2PA) paa alle websites.
//
// Det her er den eneste del af NoAI der ikke bygger paa en liste over navngivne
// mennesker. Den laeser hvad billedet SELV erklaerer: C2PA-manifestet, som Adobe,
// OpenAI, Google og Leica skriver ind i filen. Vi gaetter ikke - vi kigger efter
// en erklaering nogen har lagt der med vilje.
//
// Vi validerer IKKE signaturen. Til det skal der et helt C2PA-bibliotek og en
// kaede af rodcertifikater, og gevinsten er lille: en forfalsket erklaering om at
// noget ER AI-genereret er ikke et angreb nogen har interesse i at udfoere.
// Vi laeser altsaa erklaeringen, ikke beviset - og siger det med rene ord.

(() => {
  "use strict";

  const MIN_PX = 180;          // avatarer og ikoner er ikke besvaeret vaerd
  const MAX_SAMTIDIGE = 3;
  const CACHE_MAX = 400;       // uden loft vokser den for hver unik URL i fanens levetid
  const MAERKE = "noai-c2pa-mark";

  let taendt = false;
  let doed = false;
  const set = new Map();       // url -> Promise<dom>. IKKE en dom-streng: to <img>
                               // med samme src er almindeligt (CDN-miniaturer, logoer),
                               // og med en streng fik nummer to "pending" som svar og
                               // blev aldrig maerket.
  let ivaerk = 0;
  const koe = [];

  const erDoed = (m) => /context invalidated|Extension context/i.test(m || "");
  const send = (msg) => new Promise((svar) => {
    if (doed) return svar(null);
    try {
      chrome.runtime.sendMessage(msg, (r) => {
        const f = chrome.runtime.lastError;
        if (f) { if (erDoed(f.message)) doed = true; return svar(null); }
        svar(r);
      });
    } catch (e) { if (erDoed(e && e.message)) doed = true; svar(null); }
  });

  const brugbar = (img) =>
    img.currentSrc &&
    /^https?:/.test(img.currentSrc) &&
    img.naturalWidth >= MIN_PX &&
    img.naturalHeight >= MIN_PX;

  // Vi roerer ALDRIG sidens egne styles. Et "position: relative" paa en fremmed
  // beholder flytter alle dens absolut placerede boern og oedelaegger layout - men
  // uden det kunne maerket ikke placeres, og foerste forsoeg endte derfor med at
  // springe over paa naesten alle sider. Loesningen er et lag vi selv ejer, lagt
  // oven paa siden, hvor hvert maerke placeres efter billedets egen position.

  let lag = null;
  const maerkede = new Map();   // img -> badge

  function sikrLag() {
    if (lag && lag.isConnected) return lag;
    lag = document.createElement("div");
    lag.id = "noai-c2pa-lag";
    document.documentElement.appendChild(lag);
    return lag;
  }

  let placerPlanlagt = false;
  function placer() {
    if (placerPlanlagt) return;
    placerPlanlagt = true;
    requestAnimationFrame(() => {
      placerPlanlagt = false;
      for (const [img, badge] of maerkede) {
        if (!img.isConnected) { badge.remove(); maerkede.delete(img); continue; }
        const r = img.getBoundingClientRect();
        const synlig = r.bottom > 0 && r.top < innerHeight && r.right > 0 && r.left < innerWidth
                       && r.width > 40 && r.height > 20;
        badge.style.display = synlig ? "block" : "none";
        if (synlig) { badge.style.left = Math.round(r.left) + "px"; badge.style.top = Math.round(r.top) + "px"; }
      }
    });
  }

  function maerk(img, svar) {
    const dom = svar && svar.dom;
    // Tre erklaeringer, tre ordlyde. "ai-derived" er et billede hvis eget manifest
    // ikke siger noget om kilden, men som er aabnet fra (parentOf) et billede der
    // erklaerer AI - fx et AI-billede der er beskaaret i Photoshop og gemt igen.
    if (dom !== "ai" && dom !== "ai-composite" && dom !== "ai-derived") return;
    if (maerkede.has(img)) return;
    img.dataset.noaiC2pa = dom;
    const m = document.createElement("span");
    m.className = MAERKE;
    m.textContent = dom === "ai-composite" ? "Contains AI — declared"
                  : dom === "ai-derived" ? "AI-derived — declared"
                  : "AI — declared by the file";
    const hvem = svar.generator ? " Generator: " + svar.generator + "." : "";
    m.title = (dom === "ai-composite"
        ? "This image's own Content Credential states it contains AI-generated elements."
        : dom === "ai-derived"
        ? "This image's own Content Credential records that it was edited from an image declared as AI-generated."
        : "This image's own Content Credential states it was generated by AI.")
      + hvem
      + " NoAI reads the declaration; it does not verify the signature.";
    sikrLag().appendChild(m);
    maerkede.set(img, m);
    placer();
  }

  addEventListener("scroll", placer, { passive: true, capture: true });
  addEventListener("resize", placer, { passive: true });

  async function undersoeg(img) {
    const url = img.currentSrc;
    if (!set.has(url)) {
      if (set.size >= CACHE_MAX) set.delete(set.keys().next().value);
      set.set(url, send({ type: "c2pa", url }).then((s) => s || { dom: "none" }));
    }
    maerk(img, await set.get(url));
  }

  function naeste() {
    while (ivaerk < MAX_SAMTIDIGE && koe.length) {
      const img = koe.shift();
      ivaerk++;
      undersoeg(img).finally(() => { ivaerk--; naeste(); });
    }
  }

  // Kun billeder der faktisk er i syne. Ellers ville en lang side koste hundredvis
  // af opslag for noget brugeren aldrig ser.
  // Et billede kan vaere (a) faerdigt og brugbart, (b) faerdigt og for lille, eller
  // (c) ikke faerdigt endnu. Foerste udgave lyttede kun efter "load" - men er
  // billedet ALLEREDE faerdigt, kommer den haendelse aldrig igen, og billedet var
  // tabt for altid. Paa en statisk side er det stort set alle.
  function proev(img) {
    if (doed || !taendt) return;
    if (brugbar(img)) { koe.push(img); naeste(); return; }
    if (!img.complete) img.addEventListener("load", () => proev(img), { once: true });
  }

  const iSyne = new IntersectionObserver((poster) => {
    for (const p of poster) {
      if (!p.isIntersecting) continue;
      iSyne.unobserve(p.target);
      proev(p.target);
    }
  }, { rootMargin: "200px" });

  function saml() {
    if (!taendt || doed) return;
    for (const img of document.images) {
      if (img.dataset.noaiC2paSet) continue;
      img.dataset.noaiC2paSet = "1";
      iSyne.observe(img);
    }
  }

  let planlagt = false;
  const planlaeg = () => {
    if (planlagt || doed) return;
    planlagt = true;
    const koer = () => { planlagt = false; saml(); };
    if (document.hidden) setTimeout(koer, 500); else requestAnimationFrame(koer);
  };

  async function start() {
    const s = await send({ type: "c2paEnabled" });
    taendt = !!(s && s.enabled);
    if (!taendt) return;
    new MutationObserver(planlaeg).observe(document.documentElement,
      { childList: true, subtree: true });
    planlaeg();
  }

  chrome.storage.onChanged.addListener((c, o) => {
    if (o !== "local" || !c.c2pa || doed) return;
    // Tidligere stod her location.reload(). Scriptet koerer paa http(s)://*/*, saa
    // ét klik paa kontakten genindlaeste HVER aaben fane samtidig: tabte formularer,
    // tabt scroll-position, afbrudt video. Paa en maskine med 40 faner ligner det
    // et browser-nedbrud.
    taendt = !!c.c2pa.newValue;
    if (taendt) planlaeg();
    else { for (const [, b] of maerkede) b.remove(); maerkede.clear(); }
  });

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();
})();
