// NoAI - Content Credentials (C2PA) paa alle websites.
//
// Det her er den eneste del af NoAI der ikke bygger paa en liste over navngivne
// mennesker. Den laeser hvad billedet SELV erklaerer: C2PA-manifestet, som Adobe,
// OpenAI, Google og Leica skriver ind i filen. Vi gaetter ikke - vi kigger efter
// en erklaering nogen har lagt der med vilje.
//
// Vi validerer IKKE signaturen. Til det skal der et helt C2PA-bibliotek og en
// kaede af rodcertifikater, og gevinsten er lille: en forfalsket erklaering om at
// noget ER AI-genereret er ikke et angreb nogen har interesse i at udfoere.
// Vi laeser altsaa erklaeringen, ikke beviset - og siger det med rene ord.

(() => {
  "use strict";

  const MIN_PX = 180;          // avatarer og ikoner er ikke besvaeret vaerd
  const MAX_SAMTIDIGE = 3;
  const MAERKE = "noai-c2pa-mark";

  let taendt = false;
  let doed = false;
  const set = new Map();       // url -> "ai" | "camera" | "none" | "pending"
  let ivaerk = 0;
  const koe = [];

  const erDoed = (m) => /context invalidated|Extension context/i.test(m || "");
  const send = (msg) => new Promise((svar) => {
    if (doed) return svar(null);
    try {
      chrome.runtime.sendMessage(msg, (r) => {
        const f = chrome.runtime.lastError;
        if (f) { if (erDoed(f.message)) doed = true; return svar(null); }
        svar(r);
      });
    } catch (e) { if (erDoed(e && e.message)) doed = true; svar(null); }
  });

  const brugbar = (img) =>
    img.currentSrc &&
    /^https?:/.test(img.currentSrc) &&
    img.naturalWidth >= MIN_PX &&
    img.naturalHeight >= MIN_PX;

  function maerk(img, dom) {
    if (dom !== "ai") return;
    if (img.dataset.noaiC2pa === "ai") return;
    img.dataset.noaiC2pa = "ai";
    const vaert = img.parentElement;
    if (!vaert || vaert.querySelector("." + MAERKE)) return;
    if (getComputedStyle(vaert).position === "static") vaert.style.position = "relative";
    const m = document.createElement("span");
    m.className = MAERKE;
    // Ordlyden er praecis med vilje: billedet siger det selv, vi har ikke afgjort det.
    m.textContent = "AI — declared by the file";
    m.title = "This image carries a Content Credential stating it was generated by AI. "
            + "NoAI reads that declaration; it does not verify the signature.";
    vaert.appendChild(m);
  }

  async function undersoeg(img) {
    const url = img.currentSrc;
    if (set.has(url)) { maerk(img, set.get(url)); return; }
    set.set(url, "pending");
    const svar = await send({ type: "c2pa", url });
    const dom = (svar && svar.verdict) || "none";
    set.set(url, dom);
    maerk(img, dom);
  }

  function naeste() {
    while (ivaerk < MAX_SAMTIDIGE && koe.length) {
      const img = koe.shift();
      ivaerk++;
      undersoeg(img).finally(() => { ivaerk--; naeste(); });
    }
  }

  // Kun billeder der faktisk er i syne. Ellers ville en lang side koste hundredvis
  // af opslag for noget brugeren aldrig ser.
  const iSyne = new IntersectionObserver((poster) => {
    for (const p of poster) {
      if (!p.isIntersecting) continue;
      iSyne.unobserve(p.target);
      if (brugbar(p.target)) { koe.push(p.target); }
    }
    naeste();
  }, { rootMargin: "200px" });

  function saml() {
    if (!taendt || doed) return;
    for (const img of document.images) {
      if (img.dataset.noaiC2paSet) continue;
      img.dataset.noaiC2paSet = "1";
      iSyne.observe(img);
    }
  }

  let planlagt = false;
  const planlaeg = () => {
    if (planlagt || doed) return;
    planlagt = true;
    const koer = () => { planlagt = false; saml(); };
    if (document.hidden) setTimeout(koer, 500); else requestAnimationFrame(koer);
  };

  async function start() {
    const s = await send({ type: "c2paEnabled" });
    taendt = !!(s && s.enabled);
    if (!taendt) return;
    new MutationObserver(planlaeg).observe(document.documentElement,
      { childList: true, subtree: true });
    planlaeg();
  }

  chrome.storage.onChanged.addListener((c, o) => {
    if (o === "local" && c.c2pa && !doed) location.reload();
  });

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start);
  else start();
})();
